### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by GCHQ-Developer-530** [mi6/ic-ui-kit-test-app#10]
## Summary 
Update the repo name and references to the repo name.

## 💬 Description 
A job for an admin, update the repo to be prefixed with `ic-` like our ic-ui-kit and ic-design-system repos. 
Any references to the current repo name need to be replaced e.g. in package.json files and CONTRIBUTING.md file.

## 💰 Use value 
Improves consistency across repos.

**Comment by evenstensberg** [comment]
This is done and should be closed.
